update

diff --git a/.github/workflows/commit-test.yml b/.github/workflows/commit-test.yml
--- a/.github/workflows/commit-test.yml
+++ b/.github/workflows/commit-test.yml
@@ -61,13 +61,12 @@ jobs:
         refresh-message-position: true
         message: |
           **Either Committer Name and Email address is missing, please config that before merging** 
-          exit 1
 
-    #- name: committer info check
-    #  if: ${{ env.GIT_COMMIT_AUTHOR_NAME != 'null' || env.GIT_COMMIT_AUTHOR_EMAIL != 'null' }}
-    #  run: |
-    #    echo "Committer Name or Email is missing"
-    #    exit 1
+    - name: committer info check
+      if: ${{ env.GIT_COMMIT_AUTHOR_NAME != 'null' || env.GIT_COMMIT_AUTHOR_EMAIL != 'null' }}
+      run: |
+        echo "Committer Name or Email is missing"
+        exit 1
 
                 
     
