typo

diff --git a/.github/workflows/diff.yml b/.github/workflows/diff.yml
--- a/.github/workflows/diff.yml
+++ b/.github/workflows/diff.yml
@@ -38,9 +38,10 @@ jobs:
           for file in ${{ steps.changed-files.outputs.changed_file }}; do
             if grep -Fxq "$STRING_TO_CHECK" "$file"; then
               echo "The string '$STRING_TO_CHECK' exists in the file: $file"
+              exit 1  # To set a non-zero exit code if the string is found
             else
               echo "The string '$STRING_TO_CHECK' doesn't exist in the file: $file"
             fi                        
-          done
+          done || exit 0  # To make sure the workflow doesn't fail if no string is found
         shell: bash  
             
